[build.environment]
NODE_VERSION = "16"
NPM_FLAGS = "--version"

[[plugins]]
package = "/plugins/netlify-plugin-yarn"

[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
command = "yarn run build"
publish = ".next"
